// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPHe3dnyNvzU_Qmqg90c7toRq2T-l_EEI',
    appId: '1:252895216685:web:9eb37ca8c4c7af13fb64a4',
    messagingSenderId: '252895216685',
    projectId: 'mindease-5bd98',
    authDomain: 'mindease-5bd98.firebaseapp.com',
    storageBucket: 'mindease-5bd98.firebasestorage.app',
    measurementId: 'G-X300BDWKWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAor5TgCJdUXfxGuXbtyTmBAQCSDl40FzM',
    appId: '1:252895216685:android:60367a02f3751575fb64a4',
    messagingSenderId: '252895216685',
    projectId: 'mindease-5bd98',
    storageBucket: 'mindease-5bd98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfVHHlVYZKDBr1miDwhR0b9SlwzbwG-lw',
    appId: '1:252895216685:ios:03bf5d617743748dfb64a4',
    messagingSenderId: '252895216685',
    projectId: 'mindease-5bd98',
    storageBucket: 'mindease-5bd98.firebasestorage.app',
    iosBundleId: 'com.example.mindease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPHe3dnyNvzU_Qmqg90c7toRq2T-l_EEI',
    appId: '1:252895216685:web:4cfaf6b49bb6e6b6fb64a4',
    messagingSenderId: '252895216685',
    projectId: 'mindease-5bd98',
    authDomain: 'mindease-5bd98.firebaseapp.com',
    storageBucket: 'mindease-5bd98.firebasestorage.app',
    measurementId: 'G-6F3WL0S4RV',
  );

}